@host = http://localhost:5000

###
post {{host}}/api/user
Content-Type: application/json

{
    "UserId": "860691c3-54de-479b-9a7c-e3e5cc474127",
    "Email": "claudiu6@domain.com",
    "Password": "123",
    "FullName": "Clau"
}

###

post {{host}}/api/auth/login
Content-Type: application/json

{
    "Email": "claudiu6@domain.com",
    "Password": "123"
}
