@host = https://localhost:5003

###
post {{host}}/api/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OURCMzFERENFODI2NkY0RjM2Nzc0OEQxQTIyRjJFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjczMDkxODMsImV4cCI6MTYyNzMxMjc4MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InBheS53ZWJhcHAiLCJqdGkiOiJDRUI0RDFCQzJDMkY4RTI0QUMwQ0UzNjlFQUE0NkYwQSIsImlhdCI6MTYyNzMwOTE4Mywic2NvcGUiOlsicGF5LmN1c3RvbWVycyJdfQ.vyJuxtLiFadMewUxLGshtn6rt30_jLEdaYe2rufyaajTlN0xmiP2WPd5z--Ds2XkJ3WwTgEIomGph9zLIrjZiCfKVJy4mQLUh97rPv_3eRAWyU8LC6kxYnJXJoAPJ4ngBKQ_gVzmKBK77vNDgp0drrJVmCAisr45RHTivOrhFVPV-rMlR0ZitK7uis4F-T8n3ouLg6gwew71_Gpp0h09QTLKtfrnVEo993qJM7JfPHUP6LS68X6UKhfhZXsJNraTvas5mmr3BkqjuVT1Dchq4v5-ps5HaFFVDZewtawVoQTaAr73j6nPuthsdvb8W2ccApiskxoW1zrRQqu3hS27PA

{
    "CustomerId": "66863a53-a36b-4b42-8113-4a8eb0ef17c1"
}

###
post {{host}}/api/customer/dob
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OURCMzFERENFODI2NkY0RjM2Nzc0OEQxQTIyRjJFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjczMDkxODMsImV4cCI6MTYyNzMxMjc4MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InBheS53ZWJhcHAiLCJqdGkiOiJDRUI0RDFCQzJDMkY4RTI0QUMwQ0UzNjlFQUE0NkYwQSIsImlhdCI6MTYyNzMwOTE4Mywic2NvcGUiOlsicGF5LmN1c3RvbWVycyJdfQ.vyJuxtLiFadMewUxLGshtn6rt30_jLEdaYe2rufyaajTlN0xmiP2WPd5z--Ds2XkJ3WwTgEIomGph9zLIrjZiCfKVJy4mQLUh97rPv_3eRAWyU8LC6kxYnJXJoAPJ4ngBKQ_gVzmKBK77vNDgp0drrJVmCAisr45RHTivOrhFVPV-rMlR0ZitK7uis4F-T8n3ouLg6gwew71_Gpp0h09QTLKtfrnVEo993qJM7JfPHUP6LS68X6UKhfhZXsJNraTvas5mmr3BkqjuVT1Dchq4v5-ps5HaFFVDZewtawVoQTaAr73j6nPuthsdvb8W2ccApiskxoW1zrRQqu3hS27PA

{
    "CustomerId": "66863a53-a36b-4b42-8113-4a8eb0ef17c1",
    "DateOfBirth": "01/09/1976"
}

###
post {{host}}/api/customer/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OURCMzFERENFODI2NkY0RjM2Nzc0OEQxQTIyRjJFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjczMDkxODMsImV4cCI6MTYyNzMxMjc4MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InBheS53ZWJhcHAiLCJqdGkiOiJDRUI0RDFCQzJDMkY4RTI0QUMwQ0UzNjlFQUE0NkYwQSIsImlhdCI6MTYyNzMwOTE4Mywic2NvcGUiOlsicGF5LmN1c3RvbWVycyJdfQ.vyJuxtLiFadMewUxLGshtn6rt30_jLEdaYe2rufyaajTlN0xmiP2WPd5z--Ds2XkJ3WwTgEIomGph9zLIrjZiCfKVJy4mQLUh97rPv_3eRAWyU8LC6kxYnJXJoAPJ4ngBKQ_gVzmKBK77vNDgp0drrJVmCAisr45RHTivOrhFVPV-rMlR0ZitK7uis4F-T8n3ouLg6gwew71_Gpp0h09QTLKtfrnVEo993qJM7JfPHUP6LS68X6UKhfhZXsJNraTvas5mmr3BkqjuVT1Dchq4v5-ps5HaFFVDZewtawVoQTaAr73j6nPuthsdvb8W2ccApiskxoW1zrRQqu3hS27PA

{
    "CustomerId": "66863a53-a36b-4b42-8113-4a8eb0ef17c1",
    "Address1": "number",
    "Address2": "street",
    "CityTown": "Dublin",
    "CountyState": "Dublin",
    "Code": "d14",
    "Country": "Ireland",
    "CountryCode": "IE"
}


###
post {{host}}/api/customer/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OURCMzFERENFODI2NkY0RjM2Nzc0OEQxQTIyRjJFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjczMDkxODMsImV4cCI6MTYyNzMxMjc4MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InBheS53ZWJhcHAiLCJqdGkiOiJDRUI0RDFCQzJDMkY4RTI0QUMwQ0UzNjlFQUE0NkYwQSIsImlhdCI6MTYyNzMwOTE4Mywic2NvcGUiOlsicGF5LmN1c3RvbWVycyJdfQ.vyJuxtLiFadMewUxLGshtn6rt30_jLEdaYe2rufyaajTlN0xmiP2WPd5z--Ds2XkJ3WwTgEIomGph9zLIrjZiCfKVJy4mQLUh97rPv_3eRAWyU8LC6kxYnJXJoAPJ4ngBKQ_gVzmKBK77vNDgp0drrJVmCAisr45RHTivOrhFVPV-rMlR0ZitK7uis4F-T8n3ouLg6gwew71_Gpp0h09QTLKtfrnVEo993qJM7JfPHUP6LS68X6UKhfhZXsJNraTvas5mmr3BkqjuVT1Dchq4v5-ps5HaFFVDZewtawVoQTaAr73j6nPuthsdvb8W2ccApiskxoW1zrRQqu3hS27PA

{
    "CustomerId": "66863a53-a36b-4b42-8113-4a8eb0ef17c1"
}

###
post {{host}}/api/customer/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OURCMzFERENFODI2NkY0RjM2Nzc0OEQxQTIyRjJFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjczMDkxODMsImV4cCI6MTYyNzMxMjc4MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImNsaWVudF9pZCI6InBheS53ZWJhcHAiLCJqdGkiOiJDRUI0RDFCQzJDMkY4RTI0QUMwQ0UzNjlFQUE0NkYwQSIsImlhdCI6MTYyNzMwOTE4Mywic2NvcGUiOlsicGF5LmN1c3RvbWVycyJdfQ.vyJuxtLiFadMewUxLGshtn6rt30_jLEdaYe2rufyaajTlN0xmiP2WPd5z--Ds2XkJ3WwTgEIomGph9zLIrjZiCfKVJy4mQLUh97rPv_3eRAWyU8LC6kxYnJXJoAPJ4ngBKQ_gVzmKBK77vNDgp0drrJVmCAisr45RHTivOrhFVPV-rMlR0ZitK7uis4F-T8n3ouLg6gwew71_Gpp0h09QTLKtfrnVEo993qJM7JfPHUP6LS68X6UKhfhZXsJNraTvas5mmr3BkqjuVT1Dchq4v5-ps5HaFFVDZewtawVoQTaAr73j6nPuthsdvb8W2ccApiskxoW1zrRQqu3hS27PA

{
    "CustomerId": "66863a53-a36b-4b42-8113-4a8eb0ef17c1"
}

